{% set name = "Pint-Pandas" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 58eb37dabcfb62e9b2fe21df1a59f1371e6d007f3ee5f1403f00489d8b11548d

build:
  number: 0
  noarch: python
  script:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
    - setuptools
  run:
    - python >=3.7
    - setuptools
    - pint >=0.13
    - pandas >=1.0.4

test:
  imports:
    - pint_pandas

  commands: python -c "import pint_pandas; assert pint_pandas.__version__ == '{{ version }}'"

about:
  home: https://github.com/hgrecco/pint-pandas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Pandas support for pint
  doc_url: https://github.com/hgrecco/pint-pandas
  dev_url: https://github.com/hgrecco/pint-pandas

extra:
  recipe-maintainers:
    - hgrecco
    - znicholls
    - dopplershift
