{% set name = "Pint-Pandas" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pint_pandas-{{ version }}.tar.gz
  sha256: ec6bd1ab9c826d40fbd78ed05e1b014f7251319e0fe3f48312523accaf816b5e

build:
  number: 0
  noarch: python
  script:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools_scm >=3.4.3
    - setuptools >=61
  run:
    - python >=3.9
    - pint >=0.24
    - pandas >=2.2
    - packaging

test:
  imports:
    - pint_pandas

  commands: python -c "import pint_pandas; assert pint_pandas.__version__ == '{{ version }}'"

about:
  home: https://github.com/hgrecco/pint-pandas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Pandas support for pint
  doc_url: https://github.com/hgrecco/pint-pandas
  dev_url: https://github.com/hgrecco/pint-pandas

extra:
  recipe-maintainers:
    - hgrecco
    - znicholls
    - dopplershift
