{% set name = "Pint-Pandas" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pint_pandas-{{ version }}.tar.gz
  sha256: 735887cc02671d3a879dfeaccf493ae7b2849dddecb5be8745a6af215d5d32bf

build:
  number: 0
  noarch: python
  script:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm >=3.4.3
    - setuptools >=61
  run:
    - python >={{ python_min }}
    - pint >=0.24
    - pandas >=2.2
    - packaging

test:
  requires:
    - python {{ python_min }}
  imports:
    - pint_pandas

  commands: python -c "import pint_pandas; assert pint_pandas.__version__ == '{{ version }}'"

about:
  home: https://github.com/hgrecco/pint-pandas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Pandas support for pint
  doc_url: https://github.com/hgrecco/pint-pandas
  dev_url: https://github.com/hgrecco/pint-pandas

extra:
  recipe-maintainers:
    - hgrecco
    - znicholls
    - dopplershift
